#!/bin/bash
#
# title             : installer
# description       : installs 'newvhost'
# usage             : No parameters. Just invoke script-name.
#==============================================================================

# Check so root is running the script
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Set up variables and strings
tLOCAL="/usr/local/newvhost"
tBIN="/usr/bin/newvhost"
tINSTALL=`pwd`

# Get proper paths to binaries used
tCHOWN=$(which chown)
tMKDIR=$(which mkdir)
tCHMOD=$(which chmod)
tCP=$(which cp)
tLN=$(which ln)


#-----------------------------------------------
# Functions
#-----------------------------------------------

#
# Install newvhost script
#
function installer() {

	$tMKDIR $tLOCAL
	$tCP $tINSTALL/* $tLOCAL/
	$tCHOWN -R root:root $tLOCAL
	$tCHMOD -R 644 $tLOCAL
	$tCHMOD 755 $tLOCAL/newvhost
	$tCHMOD 755 $tLOCAL/installer

	$tLN -s $tLOCAL/newvhost $tBIN

	echo
	echo "Installation complete!"
	echo

}


#
# Main
#
installer
